#!/bin/env bash

if [ -n "$CAMDATA" ]; then
  DATA=$CAMDATA
else
  DATA=`pwd`/data
  echo "Warning: Using default DATA directory, $DATA"
fi

if [ -z "$CAMPORT" ]; then
  echo "Error: Environment variable 'CAMPORT' must be supplied."
  exit 1
fi
PORT=$CAMPORT

# Allow an option to run interactively
if [ -z "$INTERACT" ]; then
  docker run \
    --detach --name=camlistore \
    --publish $PORT:80 \
    --volume=$DATA:/data \
    leeola/camlistore
else
  docker run \
    --rm --interactive --tty \
    --publish $PORT:80 \
    --volume=$DATA:/data \
    leeola/camlistore bash
fi

# vim: set filetype=sh:
